### ISSUE TITLE
Unable to run tests on Usermode Runtime

### ISSUE THREAD

**Issue by dfreiberger** [philippleidig/TcUnit-VsTestAdapter#30]
TwinCAT now supports a "usermode" runtime, which is convenient for unit tests because it works on more development environments (for example on computers with Windows Subsystem for Linux (WSL) or HyperV enabled, where the normal TwinCAT runtime won't work). However the test adapter will require some work to support this.

Attempting to run the tests on usermode runtime currently fails in a few places.

Firstly, the unit tests assume that they are targeting a local AmsNetID. The usermode runtime uses an alternate ID, for example `192.168.4.1.1.1` is default in `C:\TwinCAT\3.1\Runtimes\UmRT_Default\start.bat`. To support running tests against usermode runtime, the net ID needs to be parameterized.

In TestRunner.cs it fails because the usermode runtime route is local but does not show up in the static routes list.
```
if(AmsNetId.LocalHost != target && AmsNetId.Local != target)
{
    var adsRemoteRoutes = TwinCATEnvironment.GetRemoteRoutes();
    var targetRoute = adsRemoteRoutes.Where(r => r.NetId.Equals(target));

    if (!targetRoute.Any())
        throw new Exception("No ADS route to target found.");
}
```

Removing or commenting this section of code allows it to proceed and to connect.

The next place it fails is in TwinCATXAEProject.cs, because it is a default single shared core config, which does not add a <Settings> entry in the tsproj file. Changing as below allows it to proceed:
```
if (realtimeSettings != null)
{
    int.TryParse(realtimeSettings.Attribute("MaxCpus")?.Value, out int maxCpuCount);
    int.TryParse(realtimeSettings.Attribute("NonWinCpus")?.Value, out int isolatedCpuCount);
    var sharedCpuCount = maxCpuCount - isolatedCpuCount;

    RealtimeSettings = new Tuple<int,int>(sharedCpuCount, isolatedCpuCount);
}
// add the section below
else 
{
    RealtimeSettings = new Tuple<int,int>(1, 0);
}
```

Finally, because the boot folder is a different location than default, it fails to find the result file. The easiest work around is to set the xUnitFilePath to `'%TC_BOOTPRJPATH%tcunit_testresults.xml'` as done by @philippleidig in the latest TcUnit version. I went ahead and did this in the PlcTestProject settings in the linked PR.

My use case for using usermode runtime or any alternate runtime is that I cannot run TwinCAT XAR locally, including the tests, because it does not work on newer generations of laptop from Lenovo due to various issues with the hardware. So tests always have to either run against a physical target, this usermode runtime, or in a virtualized environment.

To reproduce this, you can start a new usermode runtime via `C:\TwinCAT\3.1\Runtimes\UmRT_Default\start.bat` and then point the tests to `192.168.4.1.1.1`.

**Comment by dfreiberger** [comment]
See https://github.com/dfreiberger/TcUnit-VsTestAdapter/commit/6c1b410f2cbf1a0aca06cb2aaab067b2919d2545 for some changes that get this working, however they are breaking changes to the unit tests so it still requires some work to parameterize the AmsNetId and result path.

**Comment by philippleidig** [comment]
@dfreiberger  Thanks !
